[package]
name = "livecamera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
actix-web-actors = "4.3.0"
mediasoup = "0.17.0"
num_cpus = "1.16.0"
rand = "0.8.5"
serde = "1.0.204"
serde_json = "1.0.120"
tracing = "0.1.40"
tracing-actix-web = "0.7.11"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
