name: Build

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build
        working-directory: server
        run: cargo build --verbose
      - name: Run tests
        working-directory: server
        run: cargo test --verbose

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        working-directory: frontend
        run: |
          npm install
      - name: Build
        working-directory: frontend
        run: |
          npm run build
      - name: Typecheck
        working-directory: frontend
        run: |
          npm run typecheck
